export const GET_PHOTO_STARTED = 'GET_PHOTO_STARTED';
export const GET_PHOTO_SUCCESS = 'GET_PHOTO_SUCCESS';
export const GET_PHOTO_FAILED = 'GET_PHOTO_FAILED';
export const HELL_ACTION = 'HELL_ACTION';
export const GET_POST_STARTED = 'GET_POST_STARTED';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAILED = 'GET_POST_FAILED';
